# Generated by Django 5.1.4 on 2025-04-08 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_album_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('user', 'uri')},
        ),
        migrations.AlterUniqueTogether(
            name='artist',
            unique_together={('user', 'uri')},
        ),
    ]
