# Generated by Django 5.1.4 on 2025-01-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
