# Generated by Django 5.1.4 on 2025-01-19 00:06

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_profile_hue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_hue',
            field=colorfield.fields.ColorField(default='000,000,000', image_field=None, max_length=25, samples=None),
        ),
    ]
