# Generated by Django 5.1.4 on 2025-01-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_profile_hue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_hue',
            field=models.CharField(default='000,000,000', max_length=20),
        ),
    ]